AWSTemplateFormatVersion: "2010-09-09"
Description: Demo EC2 instance to test Nginx
Parameters:
  securityGroupId:
    Type: List<AWS::EC2::SecurityGroup::Id>
  publicSubnetId:
    Type: String
Resources:
  ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeType: gp2
          VolumeSize: 10
          Encrypted: "true"
      InstanceType: t2.micro
      ImageId: ami-0866a3c8686eaeeba
      KeyName: ltidemo
      SecurityGroupIds: !Ref securityGroupId
      SubnetId: !Ref publicSubnetId
      Tags:
        - Key: Name
          Value: demo-instance
        - Key: Env
          Value: Demo
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            apt update -y
            apt install nginx -y
            echo "<h1> Hello world from $(hostname-f)</h1>"> by LTI. /var/www/html/index.html
Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub 'http://${ec2Instance.PublicDnsName}'
