AWSTemplateFormatVersion: "2010-09-09"
Description: Public subnet for Demo Environment
Parameters:
  vpcId:
    Type: String
  ipv6CidrBlock:
    Type: String
  publicSubnetRouteTableId:
    Type: String
Resources:
  devPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: "true"
      AvailabilityZone: "ap-south-1a"
      CidrBlock: 192.168.1.0/24
      # Ipv6CidrBlock: !Ref ipv6CidrBlock
      MapPublicIpOnLaunch: "true"
      PrivateDnsNameOptionsOnLaunch:
        EnableResourceNameDnsAAAARecord: "true"
        EnableResourceNameDnsARecord: "true"
      Tags:
        - Key: Name
          Value: lti-demo-public-subnet
        - Key: Env
          Value: Dev
      VpcId: !Ref vpcId
  subnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref devPublicSubnet
      RouteTableId: !Ref publicSubnetRouteTableId
Outputs:
  publicSubnetId:
    Value: !Ref devPublicSubnet
    Export:
      Name: publicSubnetId
